FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY main.py .

COPY data_artifacts/ ./data_artifacts/
ENV PYTHONPATH=/app
ENV GOOGLE_API_KEY="AIzaSyBeL9GktH8nr6JnJI-WFgZxcsvcwlHyGu0"

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]